### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by lisi-github** [Ki6an/fastT5#70]
********************
when i call export_and_get_onnx_model，some errors have occurred
my gpu is v100，softwares are fastt5(0.1.4)、python(3.8.0)、torch(2.0.0)、onnx(1.13.1)、onnxruntime(1.10.0)
********************
the detailed error information is as follows：
In-place op on output of tensor.shape. See https://pytorch.org/docs/master/onnx.html#avoid-inplace-operations-when-using-tensor-shape-in-tracing-mode
In-place op on output of tensor.shape. See https://pytorch.org/docs/master/onnx.html#avoid-inplace-operations-when-using-tensor-shape-in-tracing-mode
============= Diagnostic Run torch.onnx.export version 2.0.0+cu117 =============
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================

Exporting to onnx... |##########                      | 1/3============= Diagnostic Run torch.onnx.export version 2.0.0+cu117 =============
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================

Exporting to onnx... |#####################           | 2/3============= Diagnostic Run torch.onnx.export version 2.0.0+cu117 =============
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================

Exporting to onnx... |################################| 3/3
Quantizing... |################################| 3/3
Setting up onnx model...
Traceback (most recent call last):
  File "t5_onnx.py", line 8, in <module>
    model = export_and_get_onnx_model("/root/t5_correct/t5/", "/root/t5_correct/t5_onnx/")
  File "/root/.local/conda/envs/py38/lib/python3.8/site-packages/fastT5/onnx_models.py", line 223, in export_and_get_onnx_model
Segmentation fault (core dumped)

**Comment by zzzhaoguziji** [comment]
I solved the problem like this
![微信截图_20230529153228](https://github.com/Ki6an/fastT5/assets/38344228/bbb0a2af-1ee5-4475-ac33-dcdd73e80066)

**Comment by lisi-github** [comment]
thank you,but my problem is such as this:
when i run this code [model = export_and_get_onnx_model("/root/t5_correct/t5/", "/root/t5_correct/t5_onnx/")] for gettig a onnx model, the Segmentation fault occurred

============= Diagnostic Run torch.onnx.export version 2.0.0+cu117 =============
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================

Exporting to onnx... |##########                      | 1/3============= Diagnostic Run torch.onnx.export version 2.0.0+cu117 =============
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================

Exporting to onnx... |#####################           | 2/3============= Diagnostic Run torch.onnx.export version 2.0.0+cu117 =============
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================

Exporting to onnx... |################################| 3/3
Quantizing... |################################| 3/3
Setting up onnx model...
Traceback (most recent call last):
  File "t5_onnx.py", line 7, in <module>
    model = export_and_get_onnx_model("/root/t5_correct/t5/", "/root/t5_correct/t5_onnx/")
  File "/root/.local/conda/envs/py38/lib/python3.8/site-packages/fastT5/onnx_models.py", line 223, in export_and_get_onnx_model
Segmentation fault (core dumped)

**Comment by zzzhaoguziji** [comment]
> 

This should be the same
![微信截图_20230530194516](https://github.com/Ki6an/fastT5/assets/38344228/880dcb5e-f818-4438-a91e-ba2c6bdd4c2d)

**Comment by zzzhaoguziji** [comment]
You should change n_threads to your CPU cores

**Comment by lisi-github** [comment]
I understand. Thank you very much
